### PR TITLE
Muon matching tools and toolchain

### PR DESCRIPTION
**Pull request by JackFannon**
Contains tools and toolchain config for the muon matching stage of the spallation reduction.

There are a couple of additions to the data model; these mainly include a flag to identify if particles are muons so that they can skip a portion of the toolchain and deques to contain the muon candidates and lowe candidates. A struct, `ParticleCand` has also been created that is used to create particle candidate objects with some relevant information:
- The time of the event
- Energy of the event
- Entry number
- ID (0 for muon, 1 for lowe)
- A vector of matched event numbers
- Time difference to the matched events
- Reconstructed energy of the matched events
- The lowe common block object for that event

### CODE REVIEW

**Comment by marc1uk** [comment]
[love](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-42abf0f2e4bb9bb4dbc7f08ec1209b7201e019553299fc0ff6feaba16f971916R4) [it](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-42abf0f2e4bb9bb4dbc7f08ec1209b7201e019553299fc0ff6feaba16f971916R11)

**Comment by marc1uk** [comment]
I notice the ODCut tool rejects events with OD activity.... but only if the DataModel variable `MuonEventFlag` is false, which feels like a bit of a trap. I wonder if at least the tool should be renamed.
Also, what's the significance of [this 500 - 1300ns window](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-beecc31a38e6607112a151abb9a19c2d6f4b6b45a7375cabcd94919791d1dba1R61)? It seems kinda odd to be cutting events with OD activity up to 1.3us after the lowe candidate.... what's the logic here?

**Comment by marc1uk** [comment]
[There can be](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-41ec0ec4007eab120b8862b48062a17ad79e965847c53921e4a9b9e4f037fb85R69) [no bad fits](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-41ec0ec4007eab120b8862b48062a17ad79e965847c53921e4a9b9e4f037fb85R76).... :japanese_ogre: 

Isn't muboy the general standard? Why are you using something else, and [skipping muboy](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-41ec0ec4007eab120b8862b48062a17ad79e965847c53921e4a9b9e4f037fb85R94) ... but then still checking [muboy_ntrack](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-41ec0ec4007eab120b8862b48062a17ad79e965847c53921e4a9b9e4f037fb85R104)?

What happened with [applying lfmufit and bff](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-41ec0ec4007eab120b8862b48062a17ad79e965847c53921e4a9b9e4f037fb85R182)?

But then muboy [does get applied](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R335) later... albeit muboy zbs. What's the significance of the zbs? is this for zbs files only?
Why are you fitting the muon twice?

**Comment by marc1uk** [comment]
I notice you've [started](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-a398ed4d1791324d409262eddb697d95a556630bf3325b7734a6f4c956e899c5R1) [writing](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-332ae4c24ec8a11d9958d8809f88f3cd16f67e305041f9b7859425089c764844R2) [Fortran](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-d63b8a5f8073825b650e9153754ced317fff04ef820f03568716c29c7034dc1bR3).... as if python wasn't bad enough... 
or perhaps you're just using routines from somewhere else. I'd rather avoid the usual SK practice of making duplicates of everything we call, and instead link against the originals. Can you provide paths for where you got these, so we can link against them properly?

**Comment by marc1uk** [comment]
even worse, I see some pretty dated coding practices being used in [some of your routines](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R497), I don't suppose this `Makededx` routine happens to be in any way related to the `makededx.F` [file you added](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-b66bb848df83d26284356d29ed6d6b3c287643aab29a12befe5b25bebf3be691R1), or the `makededx` routine [commented out in fortran_routines.h](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-ae75a935a32e7d9d5655a950c448f9ae4cea1d1fd4ab3cc782019a45078fca3dR57) (possibly a reference to `$ATMPD_ROOT/src/recon/stmu/makededx.F`)?

**Comment by marc1uk** [comment]
it really feels like all [these arguments that come from standard common block variables](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R218) could be wrapped up as defaults in a wrapper. :expressionless: 
same for [this](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R442) and [this](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R427) and [this](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R418).
Thanks for digging out what they need to take so we can do that! :+1: Let's add those wrappers into fortran_routines.h

**Comment by marc1uk** [comment]
https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R631 :eyes:

**Comment by JackFannon** [comment]
> [love](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-42abf0f2e4bb9bb4dbc7f08ec1209b7201e019553299fc0ff6feaba16f971916R4) [it](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-42abf0f2e4bb9bb4dbc7f08ec1209b7201e019553299fc0ff6feaba16f971916R11)

lol, changed this last minute after creating the README

**Comment by marc1uk** [comment]
i am not a fan of [hard-coding run numbers](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-4bacbc53ac1dfa70749ae676605c708573976afb0a43bbd155fec04269b8a7b6R54). The trigger thresholds should be available in the [skruninf_](https://github.com/SuperK-Soft/SKAnalysis/blob/main/UserTools/PrintEvent/PrintEvent.cpp#L938) common block, or the [RunInfo](https://github.com/SuperK-Soft/SKAnalysis/blob/main/UserTools/PrintEvent/PrintEvent.cpp#L1838) class. 

also [these](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-4bacbc53ac1dfa70749ae676605c708573976afb0a43bbd155fec04269b8a7b6R47) [thresholds](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-4bacbc53ac1dfa70749ae676605c708573976afb0a43bbd155fec04269b8a7b6R55) [could](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-4bacbc53ac1dfa70749ae676605c708573976afb0a43bbd155fec04269b8a7b6R62) also be config variables.

As with the ODCut Tool, the fact that this only applies if the muon flag is false gives me pause.

**Comment by marc1uk** [comment]
but [y](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-f5bbe4761c4f6b4f42b667c80c802d5f30076b450e79c9e01c813bdd6b508608R80) [tho](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-f5bbe4761c4f6b4f42b667c80c802d5f30076b450e79c9e01c813bdd6b508608R82) :weary:

**Comment by marc1uk** [comment]
aren't there already bswall and effwall variables by standard? [What is this doing](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-bf0898d61d150858d8499fa56c70166ba765ef67b992c668639695751019fa84R34)?

**Comment by marc1uk** [comment]
oof, ok, i think that's all... for now

**Comment by marc1uk** [comment]
I'm tempted to rename the SpallCandidates tool to something like "MuonSearch", since it seems to be ...  searching for muons.

It's interesting that the way  you apply the software trigger is quite different to the way [I've applied the software trigger](https://github.com/SuperK-Soft/SKAnalysis/blob/main/UserTools/PrintEvent/PrintEvent.cpp#L907) when looking at this recently. Do you have an understanding of how these two methods compare? I believe `softtrg_inittrgtbl_` is called internally by `get_sub_triggers_`, but you seem to call `softtrg_inittrgtbl_` directly, followed by the legally-distinct `sofftrg_inittrgtbl`, and then access the `swtrgtbl_` common directly.... can you provide any explanation what these are doing and what the contents of `swtrgtbl_` are?  It looks like this is searching for all triggers at once?

I'm a bit surprised that the only output from this Tool seems to be a boolean flag saying that there is at least one muon. Neither the number of muons, nor the muon times, are put into the DataModel... 
In particular if the event is flagged as a muon, but the releavant muon is not the primary trigger, then it seems to me that downstream tools (which all use counter_32 for the muon time) will be referencing the time of the primary trigger, which is not the time of the muon. This could even lead to the event being dropped due to an incorrect +-60s time comparison cut in the RelicMuonMatching Tool.
Also, if multiple muons are found, each needs to be treated as a separate muon, both for time matching and for later spallation PDF checks.

.... btw what's the significance of a [dimuon event](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-f5bbe4761c4f6b4f42b667c80c802d5f30076b450e79c9e01c813bdd6b508608R106) in particular...?

**Comment by marc1uk** [comment]
are you supposed to be [passing the HitCuts Tool the WallCutConfig file](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-cded3eed7c1ae70379bc07878613ab941e4118f9e860d9d873d7c29823e16575R6)? :sweat_smile:

**Comment by marc1uk** [comment]
Perhaps the HitsCut Tool should skip events if there's [no hits in the SKQ common block](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-ae1eb9adfbbaaee56cd1e1ac15d33cd9757d5b041408d01300a7080d4fd88946R39). It seems like there's probably something wrong if that's the case. Perhaps that could even be done in the TreeReader, even...

**Comment by marc1uk** [comment]
[hard-coded threshold](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-beecc31a38e6607112a151abb9a19c2d6f4b6b45a7375cabcd94919791d1dba1R72). (making notes for myself here)

**Comment by marc1uk** [comment]
The RelicCandidates tool seems  a bit redundant. It basically just makes a new flag `newRelic` which is the negation of `newMuon`. The flag seems redundant.

**Comment by marc1uk** [comment]
We are missing your `SkipTriggers` Tool.
On the other hand we have `WriteMatchedInfo`, `WriteSpallCand` and `ReconstructMatchedMuons`, which aren't in the `SpallReduction` Toolchain.... 
It looks like `ReconstructMatchedMuons` is a stripped down version of the `RelicMuonMatching::WriteMuonInfo` method (missing the dedx stuff), `WriteSpallCand` is a copy of `RelicMuonMatching::WriteRelicInfo`, and `WriteMatchedInfo` is a bit of extra branch setting that also gets rolled into both the `RelicMuonMatching` methods. 
It does seems like these methods would be more sensible as standalone Tools, so perhaps this could be fixed up and moved from `RelicMuonMatching`.

**Comment by marc1uk** [comment]
Is the [watert](https://github.com/SuperK-Soft/SKAnalysis/pull/7/files#diff-969a35fb0c17812e39e77aeeaaf7e76668aac824993e4dc5e0bcbc496e95f317R372) in RelicMuonMatching::WriteMuonInfo actually being used? It looks like it just gets retrieved, but then.... nothing is done with it?

**Comment by marc1uk** [comment]
OK, ended up doing a fair bit of work to bring this up to snuff, and then got carried away with other changes.
Upshot is these are now encapsulated in PR #8 so i'll close this one.

**Pull request closed without merging**
