### PR TITLE
Fitter

### PR DESCRIPTION
**Pull request by ekneale**
**Vertex fitter:**

Single-event fitter replicates lf_allfit with the option to use direct bonsai functions or via the bonsaifit function in bscalls.cc.

Can choose hit data from tqreal branch, or SK common blocks so there is some additional flexibility. Sample config file in configfiles/Fitter.

Also calculates the rest of the lowe variables but still using the Fortran functions - note that some of these do not save correctly to the LOWE.linfo array.

**Combined fitter:**

Fits pairs of events where there is an SHE trigger, plus a trigger in the AFT window. 

Combined fitter requires additional bonsai source code which is not included here, so CombinedFitter is not currently included in the compile. Code included for reference but bonsai source code can be provided on request.

### CODE REVIEW

**Comment by marc1uk** [comment]
hey liz, just a couple minor questions on this:
What's the motivation behind [this](https://github.com/SuperK-Soft/SKAnalysis/pull/6/files#diff-d6e54062b14a2c2e52c0a3c6b55403018f30caf3e09773e38ffb86c4a3d27a91R103)? it seems like NHITCUT is normally passed to lfallfit, but the default effect is just to bypass clusfit and jump straight to bonsai when `nqisk > NHITCUT`. So not applying lfallfit when `nqisk>NHITCUT` would result in a different behaviour of the lfallfit tool compared to just running lfallfit standalone.... 

The other things is the CombinedFitter tool is in here, but it's commented out from Unity.h and Factory.cpp, so ... what's that about?

**Comment by marc1uk** [comment]
one other point of random curiosity - perhaps i'll have more questions when i try to run it, but for now:
how does [bonsaifit_](https://github.com/SuperK-Soft/SKAnalysis/pull/6/files#diff-ae75a935a32e7d9d5655a950c448f9ae4cea1d1fd4ab3cc782019a45078fca3dR99) differ from [bonsai_fit_](https://github.com/SuperK-Soft/SKAnalysis/pull/6/files#diff-ae75a935a32e7d9d5655a950c448f9ae4cea1d1fd4ab3cc782019a45078fca3dR168)?

how does [softtrg_inittrgtbl_](https://github.com/SuperK-Soft/SKAnalysis/pull/6/files#diff-ae75a935a32e7d9d5655a950c448f9ae4cea1d1fd4ab3cc782019a45078fca3dR85) differ from [softtrg_inittrgtbl](https://github.com/SuperK-Soft/SKAnalysis/pull/6/files#diff-ae75a935a32e7d9d5655a950c448f9ae4cea1d1fd4ab3cc782019a45078fca3dR86)?

**Comment by ekneale** [comment]
Hi Marcus, requiring the number of hits to be less that nhitcut was just to speed things up when reconstructing data, as bonsai is really slow with this many hits and actually none of the signal would have that many. But yeah, it should probably be taken out for completeness and consistency.

**Comment by ekneale** [comment]
bonsai_fit_ looks quite different but I'm not sure where it is defined to be able to tell you what specifically the differences are. However, bonsaifit_ is the c++ equivalent of bonsaifit that is called by lfallfit*.F. 

In $SKOFL_ROOT/src/softtrg/softtrg_ofldata.c, softtrg_initttgtbl is called from inside softtrg_inittrgtbl_ . It applies the software trigger and populates the trigger_table and then softtrg_inittrgtbl_ extracts info from the trigger_table into the swtrgtbl_. However, I should probably revisit those functions I've included as I'm not using them all in the fitters any more.

**Comment by marc1uk** [comment]
alright, i looked over `$SKOFL_ROOT/src/softtrg/softtrg_ofldata.c` ... and i am going to take your word for it about what it's doing! :dizzy_face: 
At the least it seems like we shouldn't be calling `softtrg_inittbl` directly, and should just be using the underscored version. I can't see where trigger_table is defined, presumably some other common block, but it's not just copying across, it's also doing all sorts of masking and offsets, so i guess the contents of trigger_table are to be considered intermediary...

**Pull request merged**
